cmake_minimum_required(VERSION 3.28)
project(EEDD2526)

set(CMAKE_CXX_STANDARD 17)

add_executable(EEDD2526
        main.cpp
        MediExpress.cpp
        MediExpress.h
        ThashMedicam.cpp
        ThashMedicam.h
        Laboratorio.h
        PaMedicamento.h
        Farmacia.cpp
        Farmacia.h
        Stock.cpp
        Stock.h

        Usuario.cpp
        Usuario.h
        MallaRegular.h
        MallaRegular.cpp
        img.h
        img.cpp
)